// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMYNy7lH-p0E59z87TmmkT0nyBnp91Z44',
    appId: '1:621459760851:web:6ec22943bbf7f11106d626',
    messagingSenderId: '621459760851',
    projectId: 'instagram-clone-66c4d',
    authDomain: 'instagram-clone-66c4d.firebaseapp.com',
    storageBucket: 'instagram-clone-66c4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI14lE4S20mRPZGWuhP-mCP5Q_qhCLmX8',
    appId: '1:621459760851:android:b8c660128fc06eb506d626',
    messagingSenderId: '621459760851',
    projectId: 'instagram-clone-66c4d',
    storageBucket: 'instagram-clone-66c4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdv29dWqbEBZekDdwFwd1WgZFXdKojOgo',
    appId: '1:621459760851:ios:2349bc14eeaef81e06d626',
    messagingSenderId: '621459760851',
    projectId: 'instagram-clone-66c4d',
    storageBucket: 'instagram-clone-66c4d.firebasestorage.app',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdv29dWqbEBZekDdwFwd1WgZFXdKojOgo',
    appId: '1:621459760851:ios:2349bc14eeaef81e06d626',
    messagingSenderId: '621459760851',
    projectId: 'instagram-clone-66c4d',
    storageBucket: 'instagram-clone-66c4d.firebasestorage.app',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
